---
title: "coral_bleaching_V2"
output:
  pdf_document: default
  html_document: default
date: "2022-11-22"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}

library(tidyverse)
library(reshape2)
library(stringr)
library(maptools)
library(maps)
library(lubridate)
df <- read_csv("V2-global-bleaching-and-environmental-data.csv")
df <- df[-1, ]
head(df)
```

```{r}

df$month <- month(df$Date)
```

```{r}
df$Temperature_Celcius <- as.double(df$Temperature_Kelvin) - 273
```



```{r}
df %>% mutate(month2 = recode(month,"Jan","Feb", "Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec")) %>% mutate(month2=factor(month2, levels=c("Jan","Feb", "Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"))) %>% group_by(month2) %>% summarize(temp_mean = mean(Temperature_Celcius, na.rm=T)) %>% ggplot(aes(x=month2, y=temp_mean, fill=temp_mean)) + 
  geom_bar(stat="identity") + theme(legend.position = 'none') + 
  scale_fill_gradientn(colors=c("blue", "red")) + xlab("Months") + ylab("Temperature (°C)") + ggtitle("Average Sea Temperatures by Month")
```

```{r}
df$Longitude_Degrees <- round((df$Longitude_Degrees), 0)
df$Latitude_Degrees <- round((df$Latitude_Degrees), 0)
```

```{r}
df$bleach_per <- as.double(df$Percent_Bleaching)
df$dis_shore <- as.double(df$Distance_to_Shore)

```

```{r}
world <- map_data("world")


df %>% ggplot() + geom_raster(aes(x = Longitude_Degrees, y = Latitude_Degrees, fill=bleach_per), interpolate=T) + geom_polygon(aes(long, lat, group=group), data = world, fill = "grey80") + scale_fill_gradientn(colours = rev(rainbow(7)), na.value = NA) + theme_bw() + coord_fixed(1.3) + xlab("Longitute (deg)") + ylab("Latitude (deg)") + ggtitle("Data Collection Areas") + labs(fill = "Bleaching Percent (%)")
```


```{r}

uni <- unique(df$Ecoregion_Name)

rand_uni <- sample(uni, 8, replace=FALSE)

for (i in rand_uni) {
  
  df_new <- df %>% filter(Ecoregion_Name == i)
  print(ggplot(df_new, aes(x=Temperature_Celcius, y=bleach_per)) + geom_point() + geom_smooth(method="lm")
        + ggtitle("Temperature", i))
  
  print(ggplot(df_new, aes(x=dis_shore, y=bleach_per)) + geom_point() + geom_smooth(method="lm")
        + ggtitle("Distance to Shore", i))
  
  ml1 <- lm(Temperature_Celcius~bleach_per, data=df_new)
  r_sq1 <- summary(ml1)$r.squared
  print("Temp")
  print(r_sq1)
  
  ml2 <- lm(dis_shore~bleach_per, data=df_new)
  r_sq2 <- summary(ml2)$r.squared
  print("Dist")
  print(r_sq2)
  
}

```

```{r}
library(scales)
library(readr)

eq1 <- function(x,y) {
  m <- lm(y ~ x)
  summary(m)$r.squared
  # as.character(
  #   as.expression(
  #     substitute(italic(y) == a + b %.% italic(x)*","~~italic(r)^2~"="~r2,
  #               list(a = format(coef(m)[1], digits = 4),
  #               b = format(coef(m)[2], digits = 4),
  #               r2 = format(summary(m)$r.squared, digits = 3)))
  #  )
  # )
}

#cleaning the graph
update_bleach <- df %>% 
  filter(!(Percent_Bleaching=='nd')) %>%
  filter(!(Temperature_Mean=='nd')) %>%
  mutate_at('Percent_Bleaching', as.numeric) %>%
  mutate_at('Temperature_Mean', as.numeric) %>%
  mutate_at('Temperature_Kelvin', as.numeric) %>%
  mutate_at('Distance_to_Shore', as.numeric)

#Computations/Checking my Work
max(update_bleach$Temperature_Mean)
min(update_bleach$Temperature_Mean)
max(update_bleach$Percent_Bleaching)
min(update_bleach$Percent_Bleaching)

class(update_bleach$Temperature_Mean)
class(update_bleach$Percent_Bleaching)

#Realm_Name Plot (1)
update_bleach %>%
  ggplot(aes(Temperature_Kelvin,Percent_Bleaching,color=Realm_Name)) +
  geom_point() +
  geom_smooth(method="lm",color="black") + 
  scale_x_continuous(n.break=6) +
  facet_wrap(~Realm_Name) +
  theme(legend.position = "none") +
  xlab("Temperature (K)") +
  ylab("Bleaching Percent (%)")
eq1(update_bleach$Temperature_Kelvin, update_bleach$Percent_Bleaching)

#Turbidity | Realm facet wrapped (2)
update_bleach %>%
  ggplot(aes(Turbidity,Percent_Bleaching,color=Realm_Name)) +
  geom_point() +
  geom_smooth(method="lm",color="black") + 
  scale_x_continuous(n.break=6) +
  facet_wrap(~Realm_Name) +
  theme(legend.position = "none") +
  xlab("Turbidity (1/m)") +
  ylab("Bleaching Percent (%)")
eq1(update_bleach$Turbidity, update_bleach$Percent_Bleaching)

#Cyclone Frequency | Realm Facet Wrapped (3)
update_bleach %>%
  ggplot(aes(Cyclone_Frequency,Percent_Bleaching,color=Realm_Name)) +
  geom_point() +
  geom_smooth(method="lm",color="black") + 
  scale_x_continuous(n.break=6) +
  facet_wrap(~Realm_Name) +
  theme(legend.position = "none") +
  xlab("Cyclone Frequency") +
  ylab("Bleaching Percent (%)")
eq1(update_bleach$Cyclone_Frequency, update_bleach$Percent_Bleaching)

#Distance to Shore | Realm Facet Wrapped (4)
update_bleach %>%
  ggplot(aes(Distance_to_Shore,Percent_Bleaching,color=Realm_Name)) +
  geom_point() +
  geom_smooth(method="lm",color="black") + 
  scale_x_continuous(n.break=3) +
  facet_wrap(~Realm_Name) +
  theme(legend.position = "none") +
  xlab("Distance to Shore (m)") +
  ylab("Bleaching Percent (%)")
eq1(update_bleach$Distance_to_Shore, update_bleach$Percent_Bleaching)


```

```{R}
# While reading from csv file, replacing all "nd" with NA. 
# Once, done all numeric columns like Temperature_Kelvin, etc. automatically 
# got converted to dbl.

df <- read_csv("V2-global-bleaching-and-environmental-data.csv", na = "nd")
head(df)

colnames(df)

# For our processing from case to case basis, we have to omit all rows with NA
df_month_temp <- df  %>% 
  select(Date_Month, Temperature_Kelvin) %>% 
  na.omit()

head(df_month_temp)

# In df_month_and_avg_temp dataset, adding another column Months(i.e. Jan, Feb, ...)
df_month_and_avg_temp <- df_month_temp %>% 
  group_by(Date_Month) %>% 
  summarise(Average_Temperature_Centrigrate = mean(Temperature_Kelvin, na.rm=T) - 273.15) %>%
  mutate(Months = factor(month.abb[Date_Month], levels = month.abb))

print(df_month_and_avg_temp)

# Bar Plot (geom_bar) of Months Vs. Average Temperature
ggplot(df_month_and_avg_temp, aes(x = Months, y = Average_Temperature_Centrigrate, fill = Months)) + 
  geom_bar(na.rm=T, stat = "identity", width = 0.90) +
  labs(x = 'Month', y = 'Average Temperature (Degree Celsius)', title = 'Monthly Averagre Temperature')



# To know all Realm_Name
unique(df$Realm_Name)

# Selecting Realm_Name, Date_Year and Percent_Bleaching.
# Then taking the average (ignoring NAs) of Percent_Bleaching for a combination of Realm_Name and Date_Year.
df_year_percent_bleach_realm <- df %>% 
  select(Realm_Name, Date_Year, Percent_Bleaching) %>% 
  group_by(Realm_Name, Date_Year) %>% 
  summarize(Average_Percent_Bleaching = mean(Percent_Bleaching, na.rm=T))

# Bar Plot (geom_bar) of Percent Bleaching Vs Year for each Realm_Name
ggplot(data=df_year_percent_bleach_realm, aes(x=Date_Year, y=Average_Percent_Bleaching, fill = Date_Year, color = Date_Year)) +
  geom_bar(na.rm=T, stat="identity") + 
  facet_wrap(~Realm_Name) +
  labs(x = 'Year', y = 'Bleaching Percent', title = 'Bar Plot - Year Vs Bleaching Percent')


df_Tropical_Atlantic <- df_year_percent_bleach_realm %>%
  filter(Realm_Name == 'Tropical Atlantic')

# Bar Plot (geom_bar) of Percent Bleaching Vs Year for Tropical Atlantic
ggplot(data=df_Tropical_Atlantic, aes(x=Date_Year, y=Average_Percent_Bleaching)) +
  geom_bar(na.rm=T, stat="identity", fill = 'skyblue') +
  scale_x_continuous(limits = c(1980,2020), breaks = seq(1980,2020,5), minor_breaks = seq(1980, 2020,1)) +
  scale_y_continuous(limits = c(0,100), breaks = seq(0,100,10), minor_breaks = seq(0,100,2)) +
  labs(x = 'Year', y = 'Bleaching Percent', title = 'Bar Plot - Year Vs Bleaching Percent of Tropical Atlantic')



# Scatter Plot of Distance_to_Shore Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=Distance_to_Shore, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Distance to Shore (m)', y = 'Bleaching Percent', title = 'Scatter Plot - Distance to Shore Vs Bleaching Percent')


# Scatter Plot of Cyclone_Frequency Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=Cyclone_Frequency, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Cyclone Frequency', y = 'Bleaching Percent', title = 'Scatter Plot - Cyclone Frequency Vs Bleaching Percent')


# Scatter Plot of Depth_m Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=Depth_m, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Depth (m)', y = 'Bleaching Percent', title = 'Scatter Plot - Depth Vs Bleaching Percent')


# Scatter Plot of Temperature Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=Temperature_Kelvin - 273.15, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Temperature (Degree Celsius)', y = 'Bleaching Percent', title = 'Scatter Plot - Temperature Vs Bleaching Percent')


# Scatter Plot of Windspeed Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=Windspeed, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Windspeed (m/hr)', y = 'Bleaching Percent', title = 'Scatter Plot - Windspeed Vs Bleaching Percent')


# Scatter Plot of SSTA Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=SSTA, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Sea Surface Temperature Anomaly (Degree Celsius)', y = 'Bleaching Percent', title = 'Scatter Plot - SSTA Vs Bleaching Percent')


# Scatter Plot of TSA Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=TSA, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Thermal Stress Anomaly (Degree Celsius)', y = 'Bleaching Percent', title = 'Scatter Plot - TSA Vs Bleaching Percent')


# Scatter Plot of ClimSST Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=ClimSST - 273.15, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Climatological Sea Surface Temperature (Degree Celsius)', y = 'Bleaching Percent', title = 'Scatter Plot - ClimSST Vs Bleaching Percent')


# Scatter Plot of Turbidity Vs Percent_Bleaching for all Realm_Name
ggplot(df, aes(x=Turbidity, y=Percent_Bleaching)) +
  geom_point(na.rm=T, color = 'blue', size = 0.25) +
  facet_wrap(~Realm_Name) +
  labs(x = 'Turbidity (1/m)', y = 'Bleaching Percent', title = 'Scatter Plot - Turbidity Vs Bleaching Percent')



# Visualizing Correlation Matrix for important columns
df_cor <- df %>% select(Percent_Bleaching, Distance_to_Shore,
                        Cyclone_Frequency, Depth_m, Temperature_Kelvin,
                        Windspeed, SSTA, TSA, ClimSST, Turbidity)
``` 

```{R}
df_cor %>% na.omit() %>% select_if(is.numeric) %>% cor %>%
  as.data.frame %>% rownames_to_column %>% pivot_longer(-1) %>%
  ggplot(aes(rowname, name, fill=value)) + geom_tile(color="white") + 
  geom_text(aes(label=round(value,2)), size=3.3, color="white") +
  theme(text = element_text(size=10), axis.text.x = element_text(angle=90, hjust=1)) +
  labs(x = '', y = '', title = 'Correlation Matrix') +
  coord_fixed()
```
Percent Bleaching, is positively correlated with Depth_m, TSA, Temperature_Kelvin, SSTA, Cyclone_Frequency, Windspeed and Distance_to_Shore in this order (i.e. Depth_m is maximum and Distance_to_Shore is minimum).

Percent Bleaching is negatively correlated with Turbidity and ClimSST (Turbidity is negatively maximum and ClimSST is negatively minimum).
